name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # Checkout repository
    - name: Checkout Repo
    - uses: actions/checkout@v4

    # Setup .NET Core SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "7.0"

    # ASP.Net Back end
    - name: ASP.Net
      run: |
        cd BetterSpotifySearchAPI
        dotnet restore
        dotnet build --no-restore -c Release

    # Xunit Tests
    - name: Xunit Tests
      run: |
        cd BetterSpotifySearchAPI.Tests
        dotnet restore
        dotnet test --no-restore --verbosity normal

