name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # Checkout repository
    - uses: actions/checkout@v4

    # Setup .NET Core SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "7.0"

    # Restore dependencies and build .NET back end
    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet build --no-restore -c Release

    # Run XUnit tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    